### ISSUE TITLE
Variable innecesaria. Refactoriza

### ISSUE THREAD

**Issue by lmagarin** [FcoJavierGlez/ExamenAbrilProgram#10]
https://github.com/FcoJavierGlez/ExamenAbrilProgram/blob/f54ec4f8f1be9e48b2dec59061d00270b4f8e6f9/almacen/src/gestisimal/utiles/Teclado.java#L29
Variable innecesaria. Refactoriza
Revisa todos los códigos con este error.
Puedes utilizar Refactoring.../inline

**Comment by FcoJavierGlez** [comment]
Corregido también en el Issue#11, se me ha pasado cerrar ambos en el mismo commit. Aquí dejo la referencia al commit donde he corregido ambos.

[commit 1928093bc39a42e9c90bdc3332ccef503d2b0c20](https://github.com/FcoJavierGlez/ExamenAbrilProgram/commit/1928093bc39a42e9c90bdc3332ccef503d2b0c20)
