### ISSUE TITLE
Objetos en java en minúscula. Sólo las clases/interfaces en mayúsculas. Buenas prácticas

### ISSUE THREAD

**Issue by lmagarin** [FcoJavierGlez/ExamenAbrilProgram#6]
https://github.com/FcoJavierGlez/ExamenAbrilProgram/blob/beb33496c50d6a334f32cdf50c98711c98e65a51/almacen/src/gestisimal/almacen/Almacen.java#L41
Objetos en java en minúscula. Sólo las clases/interfaces en mayúsculas. Buenas prácticas

**Comment by FcoJavierGlez** [comment]
Me resulta bastante extraño haberme equivocado en algo como esto, siempre he respetado el camelCase, habrá sido algún despiste. En cualquier caso está arreglado.
