### ISSUE TITLE
El método almacen.remove() devolverá true/false

### ISSUE THREAD

**Issue by lmagarin** [FcoJavierGlez/ExamenAbrilProgram#7]
https://github.com/FcoJavierGlez/ExamenAbrilProgram/blob/beb33496c50d6a334f32cdf50c98711c98e65a51/almacen/src/gestisimal/almacen/Almacen.java#L53

El método almacen.remove() devolverá true/false
https://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html#remove(java.lang.Object)
Debes crear el constructor new Article(codigo)

**Comment by FcoJavierGlez** [comment]
He reabierto el Issue al ver que no había corregido bien el fallo. Me parece que ahora está mejor.
